### ISSUE TITLE
Mining issues

### ISSUE THREAD

**Issue by fabioticconi** [caethan/urw-sufficiency#11]
Crushing stones does not consume the stone, which is weird. My proposal:

```
// Crush stone to rocks
.Crush stone. "Rock" (5) *CARPENTRY* -C- [effort:4] [phys:stance,arms,hands] /30/ [noquality]
{Stone} [ground]
{Stone} [ground] [remove]
[NAME:Rock]
```

That is: to crush a stone you need to stones, but only one gets removed.

Also mining big stones should maybe require an axe, until a recipe for a pickaxe is available?

**Comment by caethan** [comment]
Sorry for the delay - job changes, etc., etc.

Thanks for the bug report, added [remove] to the stone and figured I'd use the Hammer as a temporary tool for stone mining/crushing for now.
