### ISSUE TITLE
Regularize porridge and soup recipes

### ISSUE THREAD

**Issue by brettolsen** [caethan/urw-sufficiency#19]
I'd like to have it set up patchwise with a max of say, 4, such that making all 4 with all ingredients will fully fill a pot, but you can make smaller batches as well.

**Comment by caethan** [comment]
Looks like patchwise is broken with [boil] and [bake] cooking recipes:  it duplicates the pot, so we can't do this right now.

**Comment by caethan** [comment]
Updated cookery recipes more generally.
